insert into servico values ( 1, 'Encanador(a)');
insert into servico values ( 2, 'Eletricista');
insert into servico values ( 3, 'Marceneiro(a)');
insert into servico values ( 4, 'Pedreiro(a)');
insert into servico values ( 5, 'Jardineiro(a)');
insert into servico values ( 6, 'Domestica');
insert into servico values ( 7, 'Lavador de Carros');
insert into servico values ( 8, 'Cozinheiro(a)');
insert into servico values ( 9, 'Engenheiro(a)');
insert into servico values ( 10, 'Enfermeiro(a)');
insert into servico values ( 11, 'Babá');
insert into servico values ( 12, 'Motorista');
insert into servico values ( 13, 'Mecânico(a)');
insert into servico values ( 14, 'Eletricista de Veículos');
insert into servico values ( 15, 'Contador(a)');
insert into servico values ( 16, 'Professor(a) de Inglês');
insert into servico values ( 17, 'Professor(a) de Alemão');
insert into servico values ( 18, 'Professor(a)');
insert into servico values ( 19, 'Veterinário(a)');
insert into servico values ( 20, 'Arquiteto(a)');
insert into servico values ( 21, 'Personal Treiner');
insert into servico values ( 22, 'Químico(a)');
insert into servico values ( 23, 'Conselheiro(a)');
insert into servico values ( 24, 'Psicologo(a)');
insert into servico values ( 25, 'Dentista');
insert into servico values ( 26, 'Passeador(a) de Animais');  
insert into servico values ( 27, 'Técnico em informatica'); 
insert into servico values ( 28, 'Serviços Gerais');

insert into usuario values (0, '12345678901', 'Administrador', 'admin@admin.com', 'F6FDFFE48C908DEB0F4C3BD36C032E72', 'Rua 2 de Setembro', 1234, 1, '12341234', 1, 1, 4);

insert into prestador_servico values (1, 1, 2, 80);
insert into prestador_servico values (2, 1, 4, 50);
insert into prestador_servico values (3, 1, 7, 60);

insert into cidade values (1, 'Blumenau');
insert into cidade values (2, 'Brusque');
insert into cidade values (3, 'Gaspar');
insert into cidade values (4, 'Jaraguá do Sul');
insert into cidade values (5, 'Indaial');
insert into cidade values (6, 'Ilhota');
insert into cidade values (7, 'Itajai');
insert into cidade values (8, 'Navegantes');
insert into cidade values (9, 'Pomerode');


insert into bairro values (1, 'Água Verde', 1);
insert into bairro values (2, 'Badenfurt', 1); 
insert into bairro values (3, 'Boa Vista', 1);
insert into bairro values (4, 'Bom Retiro', 1);
insert into bairro values (5, 'Centro', 1); 
insert into bairro values (6, 'Escola Agrícola', 1);
insert into bairro values (7, 'Fidélis', 1);
insert into bairro values (8, 'Fortaleza', 1);
insert into bairro values (9, 'Fortaleza Alta', 1);
insert into bairro values (10, 'Garcia', 1);
insert into bairro values (11, 'Glória', 1);
insert into bairro values (12, 'Itoupava Central', 1);
insert into bairro values (13, ' Itoupava  Norte ', 1);
insert into bairro values (14, 'Itoupavazinha', 1);  
insert into bairro values (15, 'Jardim Blumenau', 1); 
insert into bairro values (16, 'Nova Esperança', 1); 
insert into bairro values (17, 'Ponta Aguda', 1); 
insert into bairro values (18, 'Progresso', 1); 
insert into bairro values (19, 'Ribeirão Fresco', 1); 
insert into bairro values (20, 'Salto Do Norte', 1); 
insert into bairro values (21, 'Salto Weissbash', 1); 
insert into bairro values (22, 'Testo Salto', 1); 
insert into bairro values (23, 'Tribess', 1); 
insert into bairro values (24, 'Valparaíso', 1); 
insert into bairro values (25, 'Velha', 1); 
insert into bairro values (26, ' Velha Central ', 1); 
insert into bairro values (27, ' Velha Grande ', 1);
insert into bairro values (28, ' Vila formosa ', 1); 
insert into bairro values (29, ' Vila Itoupava ', 1);
insert into bairro values (30, ' Vila Nova ', 1); 

insert into bairro values (31, 'Alto Gasparinho', 2);
insert into bairro values (32, 'Arraial D Ouro', 2); 
insert into bairro values (33, 'Barracão', 2);
insert into bairro values (34, 'Bateias', 2);
insert into bairro values (35, 'Bela Vista', 2); 
insert into bairro values (36, 'Belchior Alto', 2);
insert into bairro values (37, 'Belchior Central', 2);
insert into bairro values (38, 'Centro', 2);
insert into bairro values (39, 'Coloninha', 2);
insert into bairro values (30, 'Figueira', 2);
insert into bairro values (41, 'Gaspar Alto', 2);
insert into bairro values (42, 'Gaspar Grande', 2);
insert into bairro values (43, ' Gasparinho ', 2);
insert into bairro values (44, 'Gaspar Mirim', 2);  
insert into bairro values (45, 'Lagoa', 2); 
insert into bairro values (46, 'Macucos', 2); 
insert into bairro values (47, 'Margem Esquerda', 2); 
insert into bairro values (48, 'Poço Grande', 2); 
insert into bairro values (49, 'Santa Teresinha', 2); 
insert into bairro values (50, ' Sete de Setembro ', 2); 

insert into bairro values (51, 'Água Verde', 3);
insert into bairro values (52, 'Arapongas', 3); 
insert into bairro values (53, 'Bairro Dos Estados', 3);
insert into bairro values (54, 'Bairro Das Nações', 3);
insert into bairro values (55, 'Bairro Do Sol', 3); 
insert into bairro values (56, 'Benedito', 3);
insert into bairro values (57, 'Carijós', 3);
insert into bairro values (58, 'Centro', 3);
insert into bairro values (59, 'Encano', 3);
insert into bairro values (60, 'Estados', 3);
insert into bairro values (61, 'Estrada Areias', 3);
insert into bairro values (62, 'João Paulo II', 3);
insert into bairro values (63, ' João Paulo LI', 3);
insert into bairro values (64, 'Nações', 3);  
insert into bairro values (65, 'Passo Manso', 3); 
insert into bairro values (66, 'Polaquia', 3); 
insert into bairro values (67, 'Ribeirão das Pedras', 3); 
insert into bairro values (68, 'Ribeirão Kellerman', 3); 
insert into bairro values (69, 'Rio Morto', 3); 
insert into bairro values (70, 'Tapajós', 3); 
insert into bairro values (71, 'Warnow', 3); 

insert into bairro values (72, ' Águas Claras ', 4);
insert into bairro values (73, ' Azambuja ', 4); 
insert into bairro values (74, ' Bateas ', 4);
insert into bairro values (75, ' Cedrinho ', 4);
insert into bairro values (76, ' Cedro Alto', 4); 
insert into bairro values (77, ' Centro', 4);
insert into bairro values (78, ' Dom Joaquim', 4);
insert into bairro values (79, ' Guarani', 4);
insert into bairro values (80, ' Jardim Maluche', 4);
insert into bairro values (81, ' Limeira', 4);
insert into bairro values (82, ' Limoeiro', 4);
insert into bairro values (83, ' Nova Brasilia', 4);
insert into bairro values (84, ' Paquetá', 4);
insert into bairro values (85, ' Poço Fundo', 4);  
insert into bairro values (86, ' Ponta Russia', 4); 
insert into bairro values (87, ' Primeiro de Maio', 4); 
insert into bairro values (88, ' Primeiro de Maio', 4); 
insert into bairro values (89, ' Rio Branco', 4); 
insert into bairro values (90, ' Santa Luzia', 4); 
insert into bairro values (101, ' Santa Rita', 4); 
insert into bairro values (102, ' Santa Teresinha ', 4); 
insert into bairro values (103, ' São João', 4); 
insert into bairro values (104, ' São Luiz', 4); 
insert into bairro values (105, ' São Pedro', 4); 
insert into bairro values (106, ' Souza Cruz', 4); 
insert into bairro values (107, ' Steffen', 4); 
insert into bairro values (108, ' Tomas Coelho ', 4);
insert into bairro values (109, ' Zantão', 4); 
